name: 'Install Pip Dependencies Action'
description: 'Install pip dependencies for a project'

inputs:
  requirement-file-name:
    description: 'Name of pip requirements file'
    required: false

  extra-pip-packages:
    description: 'Extra python packages to install'
    required: false

  path:
    description: 'Directory to run the action'
    required: false
    default: ${{ github.workspace }}

runs:
  using: 'composite'
  steps:
    - name: Install Pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: Install Local Project
      shell: bash
      run: pip install --no-cache-dir -e .

    - name: Install Requirements File
      if: ${{ inputs.requirement-file-name != '' }}
      shell: bash
      run: pip install -r ${{ inputs.requirement-file-name }}

    - name: Install Additional Packages
      if: ${{ inputs.extra-pip-packages }}
      run: pip install ${{ inputs.extra-pip-packages }}
