name: Java Build Action
description: Build a Java project and upload as a build artifact
author: sean.smith [B00158319@mytudublin.ie]

inputs:
  build-command:
    description: Build command for the project
    type: string
    required: true

  build-directory:
    description: Build results directory
    type: string
    required: true

  artifact-name:
    description: Name of the artifact to upload
    type: string
    required: false
    default: java-build

  path:
    description: Directory to run the action
    type: string
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Build Java Application
      shell: bash
      working-directory: ${{ inputs.path }}
      run: ${{ inputs.build-command }}

    - name: Upload Java Build Application
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: "${{ inputs.path }}/${{ inputs.build-directory }}"
        if-no-files-found: error
