name: Python CycloneDX SBOM Creation Action
description: Create a Python CycloneDX SBOM and upload as a build artifact
author: sean.smith [B00158319@mytudublin.ie]

inputs:
  path:
    description: Directory to run the action
    type: string
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Freeze Python Environment
      shell: bash
      run: pip freeze > python-packages.txt

    - name: Install Python 3.12
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.12

    - name: Install CycloneDX
      shell: bash
      working-directory: ${{ inputs.path }}
      run: pip install cyclonedx-bom==3.11.7

    - name: Create CycloneDX SBOM
      shell: bash
      working-directory: ${{ inputs.path }}
      run: cyclonedx-py requirements python-packages.txt --outfile=sbom.json  --output-format=JSON --schema-version=1.6

    - name: Upload Python Build Repository
      uses: actions/upload-artifact@v4
      with:
        name: SBOM
        path: ${{ inputs.path }}/sbom.json
        if-no-files-found: error
