name: Eclipse Steady MVN SCA Action
description: Run Eclipse Steady MVN SCA scan
author: sean.smith [B00158319@mytudublin.ie]

inputs:
  build-directory:
    description: Build results directory
    type: string
    required: false
    default: target

  path:
    description: Directory to run the action
    type: string
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Check For File Existence
      uses: andstor/file-existence-action@v3
      with:
        files: ${{ inputs.path }}
        fail: true

    # Add the following lines to .mvn/jvm.config in the source repo
    # --add-opens=java.base/java.lang=ALL-UNNAMED
    # --add-opens=java.base/java.io=ALL-UNNAMED
    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 17
        distribution: temurin

    - name: Run Eclipse Steady (app)
      shell: bash
      working-directory: ${{ inputs.path }}
      run: mvn -Dsteady compile steady:app

    - name: Run Eclipse Steady (a2c)
      shell: bash
      working-directory: ${{ inputs.path }}
      run: mvn -Dsteady compile steady:a2c

    - name: Run Eclipse Steady (t2c)
      shell: bash
      working-directory: ${{ inputs.path }}
      run: mvn -Dsteady compile steady:t2c

    - name: Run Eclipse Steady (checkcode)
      shell: bash
      working-directory: ${{ inputs.path }}
      run: mvn -Dsteady compile steady:checkcode

    - name: Run Eclipse Steady (report)
      shell: bash
      working-directory: ${{ inputs.path }}
      run: mvn -Dsteady compile steady:report

    - name: Upload Eclipse Steady Report
      uses: actions/upload-artifact@v4
      with:
        name: sca-eclipse-steady-report
        path: |
          ${{ inputs.path }}/${{ inputs.build-directory }}/vulas/report/vulas-report.json
          ${{ inputs.path }}/${{ inputs.build-directory }}/vulas/report/vulas-report.html
        if-no-files-found: error
