name: Snyk SCA Action
description: Run Snyk SCA scan
author: sean.smith [B00158319@mytudublin.ie]

inputs:
  programming-language:
    description: Programming language to run Snyk scan against
    type: string
    required: true

  snyk-cli-version:
    description: Snyk CLI version to use
    type: string
    required: false
    default: 1.1292.1

  artifact-name:
    description: Name of the artifact to upload
    type: string
    required: false
    default: sca-snyk-report

  path:
    description: Directory to run the action
    type: string
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Check For File Existence
      uses: andstor/file-existence-action@v3
      with:
        files: ${{ inputs.path }}
        fail: true

    - name: Setup Node.js Environment
      uses: actions/setup-node@v4.0.2

    - name: Install Snyk CLI
      shell: bash
      run: npm install snyk@${{ inputs.snyk-cli-version }} -g

    # Java and JavaScript Snyk scan
    - name: Perform Snyk Test Analysis
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        snyk test \
          --all-projects \
          --severity-threshold=low \
          --prune-repeated-subdependencies \
          --dev \
          --json \
          --json-file-output=snyk-report.json || EXIT_CODE=$?
        if [[ $EXIT_CODE -eq 1 ]]; then exit 0; fi

    - name: Perform Snyk Monitor Analysis
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        snyk monitor \
          --all-projects \
          --severity-threshold=low \
          --prune-repeated-subdependencies \
          --dev \
          --json || EXIT_CODE=$?
        if [[ $EXIT_CODE -eq 1 ]]; then exit 0; fi

    # Python Snyk scan
    - name: Perform Snyk Test Analysis
      if: ${{ inputs.programming-language == 'python' }}
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        snyk test \
          --command=python3 \
          --all-projects \
          --severity-threshold=low \
          --prune-repeated-subdependencies \
          --dev \
          --json \
          --json-file-output=snyk-report.json || EXIT_CODE=$?
        if [[ $EXIT_CODE -eq 1 ]]; then exit 0; fi

    - name: Perform Snyk Monitor Analysis
      if: ${{ inputs.programming-language == 'python' }}
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        snyk monitor \
          --command=python3 \
          --all-projects \
          --severity-threshold=low \
          --prune-repeated-subdependencies \
          --dev \
          --json || EXIT_CODE=$?
        if [[ $EXIT_CODE -eq 1 ]]; then exit 0; fi

    - name: Upload Snyk Report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.path }}/snyk-report.json
