name: Snyk SCA Action
description: Run Snyk SCA scan
author: sean.smith [B00158319@mytudublin.ie]

inputs:
  programming-language:
    description: Programming language to run Snyk scan against
    type: string
    required: true

  snyk-cli-version:
    description: Snyk CLI version to use
    type: string
    required: false
    default: 1.1292.1

  snyk-file-to-scan:
    description: Snyk file to scan (Python only)
    type: string
    required: false
    default: requirements.txt

  artifact-name:
    description: Name of the artifact to upload
    type: string
    required: false
    default: sca-snyk-report

  path:
    description: Directory to run the action
    type: string
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Check For File Existence
      uses: andstor/file-existence-action@v3
      with:
        files: ${{ inputs.path }}
        fail: true

    - name: Setup Node.js Environment
      uses: actions/setup-node@v4.0.2

    - name: Install Snyk CLI
      shell: bash
      run: npm install snyk@${{ inputs.snyk-cli-version }} -g

    # Snyk returns exit code 1 if vulnerabilities are found
    - name: Perform Snyk Analysis
      if: ${{ inputs.programming-language == 'java' }}
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        snyk test \
          --package-manager=maven \
          --maven-aggregate-project \
          --severity-threshold=low \
          --json \
          --json-file-output=snyk-report.json || EXIT_CODE=$?
        if [ $EXIT_CODE -eq 1 ]; then exit 0; fi

    # Snyk returns exit code 1 if vulnerabilities are found
    - name: Perform Snyk Analysis
      if: ${{ inputs.programming-language == 'python' }}
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        snyk test \
          --command=python \
          --package-manager=pip \
          --severity-threshold=low \
          --file=${{ inputs.snyk-file-to-scan }} \
          --json \
          --json-file-output=snyk-report.json || EXIT_CODE=$?
        if [ $EXIT_CODE -eq 1 ]; then exit 0; fi

    # Snyk returns exit code 1 if vulnerabilities are found
    - name: Perform Snyk Analysis
      if: ${{ inputs.programming-language == 'javascript' }}
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        snyk test \
          --severity-threshold=low \
          --strict-out-of-sync=true \
          --json \
          --json-file-output=snyk-report.json || EXIT_CODE=$?
        if [ $EXIT_CODE -eq 1 ]; then exit 0; fi

    - name: Upload Snyk Report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.path }}/snyk-report.json
