name: Pip Dependency Tree Action
description: Generate a pip dependency tree for a project
author: sean.smith [B00158319@mytudublin.ie]

inputs:
  path:
    description: Directory to run the action
    type: string
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Install pipdeptree
      shell: bash
      working-directory: ${{ inputs.path }}
      run: pip install pipdeptree

    - name: Create Pip Dependency Tree
      shell: bash
      working-directory: ${{ inputs.path }}
      run: pipdeptree --freeze --json-tree --exclude pip,pipdeptree,setuptools,wheel,tox,build,cyclonedx-bom > python_dep_tree.json

    - name: Upload Python Dependency Tree (JSON)
      uses: actions/upload-artifact@v4
      with:
        name: python-dependency-tree
        path: ${{ inputs.path }}/python_dep_tree.json
        if-no-files-found: error
