name: 'Pip Dependency Tree Action'
description: 'Generate a pip dependency tree for project'
runs:
  using: 'composite'
  steps:
    - name: Install Python Package
      shell: bash
      run: pip install pipdeptree

    - name: Create Pip Dependency Tree
      shell: bash
      run: pipdeptree -fl --json > python_dep_tree.json

    - name: Upload Python Dependency Tree (JSON)
      uses: actions/upload-artifact@v4
      with:
        name: python-dependency-tree
        path: python_dep_tree.json
