name: CycloneDX SBOM Open Source Insights Report Action
description: Create a CSV report for all true positive vulnerabilities for a project based on it's CycloneDX SBOM
author: sean.smith [B00158319@mytudublin.ie]

inputs:
  programming-language:
    description: Programming language of the project
    type: string
    required: true

  cyclonedx-sbom-filename:
    description: Name of CycloneDX SBOM filename
    type: string
    required: true

runs:
    using: "composite"
    steps:
      - name: Install Python 3.12
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12

      - name: Install Pip Dependencies
        uses: ./.github/actions/python/install-pip-dependencies
        with:
          requirement-file-name: requirements-dev.txt
          path: ${{ github.action_path }}

      - name: Run Unit Tests
        shell: bash
        working-directory: ${{ github.action_path }}
        run: ./run_unit_tests.sh

      - name: Create CycloneDX SBOM Open Source Insights Report
        shell: bash
        run: |
          python3 -m cyclonedx_sbom_open_source_insights_report \
              --programming-language "${{ inputs.programming-language }}" \
              --cyclonedx-sbom-filename "${{ inputs.cyclonedx-sbom-filename }}"

      - name: Change Input To Lowercase
        id: input-to-lowercase
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ inputs.programming-language }}

      - name: Upload CycloneDX SBOM Open Source Insights Report
        uses: actions/upload-artifact@v4
        with:
          name: cyclonedx-sbom-open-source-insights-report
          path: cyclonedx_sbom_open_source_insights_${{ steps.input-to-lowercase.outputs.lowercase }}_report.csv
          if-no-files-found: error
