name: 'Horusec SAST Action'
description: 'Run Horusec SAST scan'

inputs:
  path:
    description: 'Directory to run the action'
    required: false
    default: ${{ github.workspace }}

runs:
    using: 'composite'
    steps:
        - name: Run Horusec Scan
          uses: fike/horusec-action@v0.2.2
          with:
            arguments: --project-path=${{ inputs.path }}/ --ignore="**/test/**" --output-format=json --json-output-file=horusec-report.json --enable-owasp-dependency-check=true --enable-shellcheck=true --return-error=false

        - name: Upload Horusec Report (JSON)
          uses: actions/upload-artifact@v4
          with:
            name: sast-horusec-report
            path: ${{ inputs.path }}/horusec-report.json
