name: Horusec SAST Action
description: Run Horusec SAST scan

inputs:
  path:
    description: Directory to run the action
    required: false
    default: ${{ github.workspace }}

  build-artifact-name:
    description: Name of Horusec build artifact
    required: false
    default: sast-horusec-report

runs:
  using: composite
  steps:
    - name: Check For File Existence
      uses: andstor/file-existence-action@v3
      with:
        files: ${{ inputs.path }}
        fail: true

    - name: Run Horusec Scan
      uses: fike/horusec-action@v0.2.2
      with:
        arguments: --project-path=${{ inputs.path }}/ --ignore="**/test/**" --output-format=json --json-output-file=horusec-report.json --enable-owasp-dependency-check=true --enable-shellcheck=true --return-error=false

    - name: Upload Horusec Report (JSON)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.build-artifact-name }}
        path: horusec-report.json
        if-no-files-found: error
