name: Node CycloneDX SBOM Creation Action
description: Create a Node CycloneDX SBOM and upload as a build artifact
author: sean.smith [B00158319@mytudublin.ie]

inputs:
  path:
    description: Directory to run the action
    type: string
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 18.x

    - name: Install CycloneDX SBOM
      shell: bash
      run: npm install --global @cyclonedx/cyclonedx-npm@1.19.0

    - name: Create CycloneDX SBOM
      shell: bash
      working-directory: ${{ inputs.path }}
      run: cyclonedx-npm package.json --package-lock-only --spec-version=1.6 --output-format=JSON --output-file=sbom.json --validate

    - name: Upload CycloneDX SBOM
      uses: actions/upload-artifact@v4
      with:
        name: cyclonedx-sbom
        path: ${{ inputs.path }}/sbom.json
        if-no-files-found: error
