name: Grype SCA Action
description: Run Grype SCA scan
author: sean.smith [B00158319@mytudublin.ie]

inputs:
  artifact-name:
    description: Name of the artifact to upload
    type: string
    required: false
    default: sca-grype-report

  path:
    description: Directory to run the action
    type: string
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Check For File Existence
      uses: andstor/file-existence-action@v3
      with:
        files: ${{ inputs.path }}
        fail: true

    - name: Perform Grype Analysis
      uses: anchore/scan-action@v3.6.4
      id: grype-scan
      with:
        path: ${{ inputs.path }}
        by-cve: true
        add-cpes-if-none: true
        severity-cutoff: critical
        fail-build: false
        output-format: json

    - name: Upload Grype Report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ steps.grype-scan.outputs.json }}
        if-no-files-found: error
