name: 'OWASP Dependency Check SCA Action'
description: 'Run OWASP Dependency Check SCA scan'

inputs:
  project-name:
    description: 'The name of the project being scanned'
    required: true

  nvd-api-key:
    description: The API Key to access the NVD API'
    required: true

  path:
    description: 'Directory to run the action'
    required: false
    default: ${{ github.workspace }}

  build-artifact-name:
    description: 'Name of Horusec build artifact'
    required: false
    default: sast-horusec-report

runs:
  using: 'composite'
  steps:
    - name: "Check For File Existence"
      uses: andstor/file-existence-action@v3
      with:
        files: ${{ inputs.path }}
        fail: true

    - name: Run OWASP Dependency Check (JSON)
      uses: dependency-check/Dependency-Check_Action@1.1.0
      env:
        JAVA_HOME: /opt/jdk
      with:
        project: ${{ inputs.project-name }}
        path: ./${{ inputs.path }}
        format: JSON
        args: >
          --enableRetired
          --enableExperimental
          --prettyPrint
          --nvdApiKey ${{ inputs.nvd-api-key }}

    - name: Run OWASP Dependency Check (HTML)
      uses: dependency-check/Dependency-Check_Action@1.1.0
      env:
        JAVA_HOME: /opt/jdk
      with:
        project: ${{ inputs.project-name }}
        path: ./${{ inputs.path }}
        format: HTML
        args: >
          --enableRetired
          --enableExperimental
          --prettyPrint
          --nvdApiKey ${{ inputs.nvd-api-key }}

    - name: Run OWASP Dependency Check (CSV)
      uses: dependency-check/Dependency-Check_Action@1.1.0
      env:
        JAVA_HOME: /opt/jdk
      with:
        project: ${{ inputs.project-name }}
        path: ./${{ inputs.path }}
        format: CSV
        args: >
          --enableRetired
          --enableExperimental
          --prettyPrint
          --nvdApiKey ${{ inputs.nvd-api-key }}

    - name: Upload OWASP Dependency Check Report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.build-artifact-name }}
        path: ${{ github.workspace }}/reports
        if-no-files-found: error
