name: OWASP Dependency Check SCA Action
description: Run OWASP Dependency Check SCA scan
author: sean.smith [B00158319@mytudublin.ie]

inputs:
  nvd-api-key:
    description: The API Key to access the NVD API
    type: string
    required: true

  project-name:
    description: The name of the project being scanned
    type: string
    required: true

  oss_index_username:
    description: The username for the OSS Index API
    type: string
    required: false

  oss_index_password:
    description: The password for the OSS Index API
    type: string
    required: false

  artifact-name:
    description: Name of the artifact to upload
    type: string
    required: false
    default: sca-owasp-dependency-check-report

  path:
    description: Directory to run the action
    type: string
    required: false
    default: ${{ github.workspace }}


runs:
  using: composite
  steps:
    - name: Check For File Existence
      uses: andstor/file-existence-action@v3
      with:
        files: ${{ inputs.path }}
        fail: true

    - name: Set Up OWASP Dependency Check Scan
      shell: bash
      run: |
        VERSION=$(curl -s https://jeremylong.github.io/DependencyCheck/current.txt)
        curl -Ls "https://github.com/jeremylong/DependencyCheck/releases/download/v$VERSION/dependency-check-$VERSION-release.zip" --output dependency-check.zip
        unzip dependency-check
        chmod +x ./dependency-check/bin/dependency-check.sh

    - name: Perform OWASP Dependency Check Analysis
      if: ${{ inputs.oss_index_username != '' && inputs.oss_index_password != '' }}
      shell: bash
      run: |
        mkdir -p ${{ inputs.path }}/owasp-reports
        ./dependency-check/bin/dependency-check.sh \
          --nvdApiKey ${{ inputs.nvd-api-key }} \
          --scan ${{ inputs.path }} \
          --project ${{ inputs.project-name }} \
          --format ALL \
          --out ${{ inputs.path }}/owasp-reports \
          --ossIndexUsername ${{ inputs.oss_index_username }} \
          --ossIndexPassword ${{ inputs.oss_index_password }} \
          --ossIndexRemoteErrorWarnOnly true
          --enableRetired \
          --enableExperimental \
          --prettyPrint \
          --disableYarnAudit

    - name: Perform OWASP Dependency Check Analysis
      if: ${{ inputs.oss_index_username == '' || inputs.oss_index_password == '' }}
      shell: bash
      run: |
        mkdir -p ${{ inputs.path }}/owasp-reports
        ./dependency-check/bin/dependency-check.sh \
          --nvdApiKey ${{ inputs.nvd-api-key }} \
          --scan ${{ inputs.path }} \
          --project ${{ inputs.project-name }} \
          --format ALL \
          --out ${{ inputs.path }}/owasp-reports \
          --ossIndexRemoteErrorWarnOnly true
          --enableRetired \
          --enableExperimental \
          --prettyPrint \
          --disableYarnAudit

    - name: Upload OWASP Dependency Check Report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.path }}/owasp-reports
        if-no-files-found: error
