name: Python Build And Upload Action
description: Build a Python project and upload as a build artifact
author: sean.smith [B00158319@mytudublin.ie]

inputs:
  path:
    description: Directory to run the action
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Build Python Package
      shell: bash
      working-directory: ${{ inputs.path }}
      run: python setup.py build

    - name: Tar Python Build
      shell: bash
      working-directory: ${{ inputs.path }}
      run: tar -czf python-build.tgz build

    - name: Upload Python Build Repository
      uses: actions/upload-artifact@v4
      with:
        name: python-build
        path: ${{ inputs.path }}/python-build.tgz
        if-no-files-found: error
