name: 'Python Build And Upload Action'
description: 'Build a Python project and upload as a build artifact'

inputs:
  path:
    description: 'Directory to run the action'
    required: false
    default: ${{ github.workspace }}

runs:
  using: 'composite'
  steps:
    - name: Build Python Package
      shell: bash
      working-directory: ${{ inputs.path }}
      run: python setup.py build

    - name: Tar Python Build
      shell: bash
      run: tar -czf python-build.tgz build

    - name: Upload Maven Build Repository
      uses: actions/upload-artifact@v4
      with:
        name: python-build
        path: python-build.tgz
