name: Python Build And Upload Action
description: Build a Python project and upload as a build artifact
author: sean.smith [B00158319@mytudublin.ie]

inputs:
  build-command:
    description: Build command to run
    type: string
    required: false
    default: python setup.py build

  build-directory:
    description: Build results directory
    type: string
    required: false
    default: dist

  path:
    description: Directory to run the action
    type: string
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Build Python Package
      shell: bash
      working-directory: ${{ inputs.path }}
      run: ${{ inputs.build-command }}

    - name: Upload Python Build Repository
      uses: actions/upload-artifact@v4
      with:
        name: python-build
        path: "${{ inputs.path }}/${{ inputs.build-directory }}"
        if-no-files-found: error
