name: Test Grype SCA Action

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  test-action-java:
    name: Test Grype SCA Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Jackson-Databind
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Java-Jackson-Databind
          ref: 1acb8ffe6eb20005114bfe18cfd5809b443789c2
          path: jackson-databind

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Build Java Application
        uses: ./experiment-resources/.github/actions/java/java-build
        with:
          build-command: mvn -Dmaven.test.skip=true clean install
          build-directory: target
          path: jackson-databind

      - name: Run Grype (SCA)
        uses: ./experiment-resources/.github/actions/sca/grype
        with:
          artifact-name: sca-grype-report-java
          path: jackson-databind

  test-action-python:
    name: Test Grype SCA Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Pillow Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Python-Pillow
          ref: 722b5d3350fbbb599fd3966e08e55547a2656cd7
          path: pillow

      - name: Install Python 3.7
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.7

      - name: Install Python Dependencies
        working-directory: pillow
        env:
          GHA_PYTHON_VERSION: 3.7
        run: .ci/install.sh

      - name: Build Python Application
        uses: ./experiment-resources/.github/actions/python/python-build
        with:
          build-command: .ci/build.sh
          build-directory: build
          path: pillow

      - name: Run Grype (SCA)
        uses: ./experiment-resources/.github/actions/sca/grype
        with:
          artifact-name: sca-grype-report-python
          path: pillow

  test-action-javascript:
    name: Test Grype SCA Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Lodash Repository
        uses: actions/checkout@v4
        with:
          repository: lodash/lodash
          ref: 1144918f3578a84fcc4986da9b806e63a6175cbb
          path: lodash

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x

      - name: Install JavaScript Dependencies
        working-directory: lodash
        run: npm ci

      - name: Build JavaScript Application
        working-directory: lodash
        run: npm run build

      - name: Package JavaScript Application
        working-directory: lodash
        run: npm pack

      - name: Run Grype (SCA)
        uses: ./experiment-resources/.github/actions/sca/grype
        with:
          artifact-name: sca-grype-report-javascript
          path: lodash
