name: Test Install Pip Dependencies Action

on: push

jobs:
  test-action-job-all-inputs:
    name: Test Install Pip Dependencies Action (All Inputs)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout Clearml
        uses: actions/checkout@v4
        with:
          repository: allegroai/clearml
          ref: f2674669265a56a8ecaed3d0147f319ee136a231
          path: clearml

      - name: Install Python 3.8
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.8

      - name: "Install Pip Dependencies"
        uses: ./main/.github/actions/python/install-pip-dependencies
        with:
          requirement-file-name: requirements.txt
          extra-pip-packages: setuptools wheel
          path: clearml

  test-action-job-partial-inputs:
    name: Test Install Pip Dependencies Action (Partial Inputs)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout Clearml
        uses: actions/checkout@v4
        with:
          repository: allegroai/clearml
          ref: f2674669265a56a8ecaed3d0147f319ee136a231
          path: clearml

      - name: Install Python 3.12
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12

      - name: "Install Pip Dependencies"
        uses: ./main/.github/actions/python/install-pip-dependencies
        with:
          path: clearml
