name: Test SonarQube SAST Action

on: push

jobs:
  test-action-mvn-job:
    name: Test SonarQube SAST Action (Maven)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout XNIO
        uses: actions/checkout@v4
        with:
          repository: xnio/xnio
          ref: 262b9acfc8a9a85aa62a40634cc14581bf6b0d7d
          path: xnio

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: adopt
          java-version: 8

      - name: Build and Upload Maven Package
        uses: ./main/.github/actions/maven/maven-build-upload
        with:
          build-command: -U -B -fae -DskipTests clean install
          path: xnio

      - name: Run SonarQube (SAST)
        uses: ./main/.github/actions/sast/sonarqube
        with:
          language: java
          sonar-token: ${{ secrets.TEST_SONAR_TOKEN }}
          sonar-host-url: ${{ secrets.TEST_SONAR_HOST_URL}}
          sonar-username: ${{ secrets.TEST_SONAR_USERNAME }}
          sonar-password: ${{ secrets.TEST_SONAR_PASSWORD }}
          sonar-project-name: test-maven
          path: xnio
          build-artifact-name: sast-sonarqube-report-maven

  test-action-python-job:
    name: Test SonarQube SAST Action (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout Clearml
        uses: actions/checkout@v4
        with:
          repository: allegroai/clearml
          ref: f2674669265a56a8ecaed3d0147f319ee136a231
          path: clearml

      - name: Run SonarQube (SAST)
        uses: ./main/.github/actions/sast/sonarqube
        with:
          language: python
          sonar-token: ${{ secrets.TEST_SONAR_TOKEN }}
          sonar-host-url: ${{ secrets.TEST_SONAR_HOST_URL}}
          sonar-username: ${{ secrets.TEST_SONAR_USERNAME }}
          sonar-password: ${{ secrets.TEST_SONAR_PASSWORD }}
          sonar-project-name: test-python
          path: clearml
          build-artifact-name: sast-sonarqube-report-python
