name: Test CycloneDX SBOM Open Source Insights Report Action

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  build-java-application:
    name: Build Application (Java)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout Jackson-Databind
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Java-Jackson-Databind
          ref: 1acb8ffe6eb20005114bfe18cfd5809b443789c2
          path: jackson-databind

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Build and Upload Maven Package
        uses: ./main/.github/actions/maven/maven-build-upload
        with:
          build-command: mvn -Dmaven.test.skip=true clean install
          path: jackson-databind

      - name: Create CycloneDX SBOM
        uses: ./main/.github/actions/maven/maven-sbom
        with:
          path: jackson-databind

  build-python-application:
    name: Build Application (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout Pillow Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Python-Pillow
          ref: 722b5d3350fbbb599fd3966e08e55547a2656cd7
          path: pillow

      - name: Install Python 3.7
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.7

      - name: Install Python Dependencies
        working-directory: pillow
        env:
          GHA_PYTHON_VERSION: 3.7
        run: .ci/install.sh

      - name: Build And Upload Python Package
        uses: ./main/.github/actions/python/python-build-upload
        with:
          build-command: .ci/build.sh
          build-directory: build
          path: pillow

      - name: Create CycloneDX SBOM
        uses: ./main/.github/actions/python/python-sbom
        with:
          path: pillow

  build-javascript-application:
    name: Build Application (JavaScript)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout Lodash Repository
        uses: actions/checkout@v4
        with:
          repository: lodash/lodash
          ref: 1144918f3578a84fcc4986da9b806e63a6175cbb
          path: lodash

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x

      - name: Install Node Dependencies
        working-directory: lodash
        run: npm ci

      - name: Build Node Application
        working-directory: lodash
        run: npm run build

      - name: Package Node Application
        working-directory: lodash
        run: npm pack

      - name: Create CycloneDX SBOM
        uses: ./main/.github/actions/node/node-sbom
        with:
          path: lodash

  test-action:
    name: Test Action
    runs-on: ubuntu-latest
    needs: [ build-java-application, build-python-application, build-javascript-application ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Open Source Insights Report
        uses: ./.github/actions/common/cyclonedx-sbom-open-source-insights-report
        with:
          programming-language: java
          cyclonedx-sbom-artifact-name: cyclonedx-sbom-maven
          cyclonedx-sbom-filename: sbom.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: cyclonedx-sbom-open-source-insights-report-java
          include-unit-tests: true

      - name: Create Open Source Insights Report
        uses: ./.github/actions/common/cyclonedx-sbom-open-source-insights-report
        with:
          programming-language: python
          cyclonedx-sbom-artifact-name: cyclonedx-sbom-python
          cyclonedx-sbom-filename: sbom.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: cyclonedx-sbom-open-source-insights-report-python
          include-unit-tests: true

      - name: Create Open Source Insights Report
        uses: ./.github/actions/common/cyclonedx-sbom-open-source-insights-report
        with:
          programming-language: javascript
          cyclonedx-sbom-artifact-name: cyclonedx-sbom-node
          cyclonedx-sbom-filename: sbom.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: cyclonedx-sbom-open-source-insights-report-javascript
          include-unit-tests: true
