name: Test Eclipse Steady SCA Action

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  test-action-java:
    name: Test Eclipse Steady SCA Action (Java)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Jackson-Databind Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Java-Jackson-Databind
          ref: d0e9952ea70d1af5c512322a32456f237afb9e9b
          path: jackson-databind

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Build Java Application
        uses: ./experiment-resources/.github/actions/java/java-build
        with:
          build-command: mvn -Dmaven.test.skip=true clean install
          path: jackson-databind

      - name: Run Eclipse Steady (SCA)
        uses: ./experiment-resources/.github/actions/sca/eclipse-steady/java
        with:
          build-directory: target
          eclipse-steady-workspace-token: 19DACF250B828F3BAB827AFA5789DB55
          eclipse-steady-host-url: ${{ secrets.TEST_ECLIPSE_STEADY_HOST_URL }}
          eclipse-steady-application-group-id: com.fasterxml.jackson
          eclipse-steady-application-artifact-id: jackson-databind
          eclipse-steady-application-version: 2.9.10.7
          eclipse-steady-project-source-directories: src
          artifact-name: sast-eclipse-steady-report-java
          path: jackson-databind

  test-action-python:
    name: Test Eclipse Steady SCA Action (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Pillow Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Python-Pillow
          ref: 722b5d3350fbbb599fd3966e08e55547a2656cd7
          path: pillow

      - name: Install Python 3.7
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.7

      - name: Install Python Dependencies
        working-directory: pillow
        env:
          GHA_PYTHON_VERSION: 3.7
        run: .ci/install.sh

      - name: Build Python Application
        uses: ./experiment-resources/.github/actions/python/python-build
        with:
          build-command: .ci/build.sh
          build-directory: build
          path: pillow

      - name: Run Eclipse Steady (SCA)
        uses: ./experiment-resources/.github/actions/sca/eclipse-steady/python
        with:
          eclipse-steady-workspace-token: 1A8CC68377BFEEA81CDF80CFA757872E
          eclipse-steady-host-url: ${{ secrets.TEST_ECLIPSE_STEADY_HOST_URL }}
          eclipse-steady-application-group-id: org.python
          eclipse-steady-application-artifact-id: pillow
          eclipse-steady-application-version: 8.3.0
          eclipse-steady-project-source-directories: src
          artifact-name: sca-eclipse-steady-report-python
          path: pillow
