name: Test Pip Dependency Tree Action

on:
  workflow_dispatch:

jobs:
  test-action-job:
    name: Test Pip Dependency Tree Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python 3.12
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12

      - name: Create Pip Dependency Tree
        uses: ./.github/actions/python/pip-dependency-tree
