name: Test SonarQube SAST Action

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  test-action:
    name: Test SonarQube SAST Action
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        category: [
          { repository: seansmith39/H6060-Java-Logback,      ref: 7ee000a0a359d239c60bb93a2f4f4ea467c38395, programming-language: java },
          { repository: seansmith39/H6060-Python-Pillow,     ref: 722b5d3350fbbb599fd3966e08e55547a2656cd7, programming-language: python },
          { repository: seansmith39/H6060-JavaScript-Lodash, ref: 1144918f3578a84fcc4986da9b806e63a6175cbb, programming-language: javascript },
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Upstream Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.category.repository }}
          ref: ${{ matrix.category.ref }}
          path: upstream-repository

      - name: Setup Java JDK
        if: ${{ matrix.category.programming-language == 'java' }}
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Build Java Application
        if: ${{ matrix.category.programming-language == 'java' }}
        uses: ./experiment-resources/.github/actions/java/java-build
        with:
          build-command: mvn -Dmaven.test.skip=true clean install
          build-directory: target
          path: upstream-repository

      - name: Run SonarQube (SAST)
        uses: ./experiment-resources/.github/actions/sast/sonarqube
        with:
          programming-language: ${{ matrix.category.programming-language }}
          sonarqube-token: ${{ secrets.TEST_SONARQUBE_TOKEN }}
          sonarqube-url: https://sonarqube.b00158319.com
          sonarqube-username: ${{ secrets.TEST_SONARQUBE_USERNAME }}
          sonarqube-password: ${{ secrets.TEST_SONARQUBE_PASSWORD }}
          sonarqube-project-key: test-${{ matrix.category.programming-language }}
          artifact-name: sast-sonarqube-report-${{ matrix.category.programming-language }}-${{ matrix.os }}
          path: upstream-repository
