name: Test CycloneDX SBOM Open Source Vulnerabilities Report Action

on:
  workflow_dispatch:

permissions:
  security-events: write

env:
  GITHUB_ORGANISATION_NAME: seansmith39
  GITHUB_UPSTREAM_CHECKOUT_PATH: upstream-repository

jobs:
  test-action-java:
    name: Test CycloneDX SBOM OSV Report Action - Java
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
        category: [
          { repository: H6060-Java-Logback, ref: 7ee000a0a359d239c60bb93a2f4f4ea467c38395 },
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Upstream Repository
        uses: actions/checkout@v4
        with:
          repository: "${{ env.GITHUB_ORGANISATION_NAME }}/${{ matrix.category.repository }}"
          ref: ${{ matrix.category.ref }}
          path: ${{ env.GITHUB_UPSTREAM_CHECKOUT_PATH }}

      - name: Set Run Unit Tests Variable
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
              echo "RUN_UNIT_TESTS=false" >> $GITHUB_ENV
          else
              echo "RUN_UNIT_TESTS=true" >> $GITHUB_ENV
          fi

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Build Java Application
        uses: ./experiment-resources/.github/actions/java/java-build
        with:
          build-command: mvn -Dmaven.test.skip=true clean install
          build-directory: "**/target"
          artifact-name: java-build-${{ matrix.os }}
          path: ${{ env.GITHUB_UPSTREAM_CHECKOUT_PATH }}

      - name: Create CycloneDX SBOM
        uses: ./experiment-resources/.github/actions/java/java-cyclonedx-sbom
        with:
          build-directory: target
          artifact-name: cyclonedx-sbom-java-${{ matrix.os }}
          path: ${{ env.GITHUB_UPSTREAM_CHECKOUT_PATH }}

      - name: Create CycloneDX OSV Report
        uses: ./experiment-resources/.github/actions/reporting/cyclonedx-sbom-osv-report
        with:
          github-api-token: ${{ secrets.TEST_GITHUB_API_TOKEN }}
          github-secret-access-token: ${{ secrets.GITHUB_TOKEN }}
          experiment-id: 1
          experiment-github-project-name: ${{ matrix.category.repository }}
          experiment-github-repository: "${{ env.GITHUB_ORGANISATION_NAME }}/${{ matrix.category.repository }}"
          experiment-programming-language: java
          cyclonedx-sbom-artifact-name: cyclonedx-sbom-java-${{ matrix.os }}
          cyclonedx-sbom-filename: sbom.json
          artifact-name: cyclonedx-sbom-osv-report-java-${{ matrix.os }}
          include-unit-tests: ${{ env.RUN_UNIT_TESTS }}

  test-action-python:
    name: Test CycloneDX SBOM OSV Report Action - Python
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
        category: [
          { repository: H6060-Python-Urllib3, ref: d1616473df94b94f0f5ad19d2a6608cfe93b7cdf },
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Upstream Repository
        uses: actions/checkout@v4
        with:
          repository: "${{ env.GITHUB_ORGANISATION_NAME }}/${{ matrix.category.repository }}"
          ref: ${{ matrix.category.ref }}
          path: ${{ env.GITHUB_UPSTREAM_CHECKOUT_PATH }}

      - name: Set Run Unit Tests Variable
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
              echo "RUN_UNIT_TESTS=false" >> $GITHUB_ENV
          else
              echo "RUN_UNIT_TESTS=true" >> $GITHUB_ENV
          fi

      # Python version < 3.8 no longer supported on MacOS
      # See issue: https://github.com/actions/runner-images/issues/9770#issuecomment-2085623315
      - name: Install Python 3.8
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        working-directory: ${{ env.GITHUB_UPSTREAM_CHECKOUT_PATH }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools build wheel nox

      - name: Build Python Application
        uses: ./experiment-resources/.github/actions/python/python-build
        with:
          build-command: python -m build
          build-directory: dist
          artifact-name: python-build-${{ matrix.os }}
          path: ${{ env.GITHUB_UPSTREAM_CHECKOUT_PATH }}

      - name: Create CycloneDX SBOM
        uses: ./experiment-resources/.github/actions/python/python-cyclonedx-sbom
        with:
          path: ${{ env.GITHUB_UPSTREAM_CHECKOUT_PATH }}
          artifact-name: cyclonedx-sbom-python-${{ matrix.os }}

      - name: Create CycloneDX OSV Report
        uses: ./experiment-resources/.github/actions/reporting/cyclonedx-sbom-osv-report
        with:
          github-api-token: ${{ secrets.TEST_GITHUB_API_TOKEN }}
          github-secret-access-token: ${{ secrets.GITHUB_TOKEN }}
          experiment-id: 2
          experiment-github-project-name: ${{ matrix.category.repository }}
          experiment-github-repository: "${{ env.GITHUB_ORGANISATION_NAME }}/${{ matrix.category.repository }}"
          experiment-programming-language: python
          cyclonedx-sbom-artifact-name: cyclonedx-sbom-python-${{ matrix.os }}
          cyclonedx-sbom-filename: sbom.json
          artifact-name: cyclonedx-sbom-osv-report-python-${{ matrix.os }}
          include-unit-tests: ${{ env.RUN_UNIT_TESTS }}

  test-action-javascript:
    name: Test CycloneDX SBOM OSV Report Action - JavaScript
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
        category: [
          { repository: H6060-JavaScript-Lodash, ref: 1144918f3578a84fcc4986da9b806e63a6175cbb },
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Upstream Repository
        uses: actions/checkout@v4
        with:
          repository: "${{ env.GITHUB_ORGANISATION_NAME }}/${{ matrix.category.repository }}"
          ref: ${{ matrix.category.ref }}
          path: ${{ env.GITHUB_UPSTREAM_CHECKOUT_PATH }}

      - name: Set Run Unit Tests Variable
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
              echo "RUN_UNIT_TESTS=false" >> $GITHUB_ENV
          else
              echo "RUN_UNIT_TESTS=true" >> $GITHUB_ENV
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x

      - name: Install JavaScript Dependencies
        working-directory: ${{ env.GITHUB_UPSTREAM_CHECKOUT_PATH }}
        run: npm ci

      - name: Build JavaScript Application
        uses: ./experiment-resources/.github/actions/javascript/javascript-build
        with:
          build-command: npm run build
          package-command: npm pack
          artifact-name: javascript-build-${{ matrix.os }}
          path: ${{ env.GITHUB_UPSTREAM_CHECKOUT_PATH }}

      - name: Create CycloneDX SBOM
        uses: ./experiment-resources/.github/actions/javascript/javascript-cyclonedx-sbom
        with:
          artifact-name: cyclonedx-sbom-javascript-${{ matrix.os }}
          path: ${{ env.GITHUB_UPSTREAM_CHECKOUT_PATH }}

      - name: Create CycloneDX OSV Report
        uses: ./experiment-resources/.github/actions/reporting/cyclonedx-sbom-osv-report
        with:
          github-api-token: ${{ secrets.TEST_GITHUB_API_TOKEN }}
          github-secret-access-token: ${{ secrets.GITHUB_TOKEN }}
          experiment-id: 3
          experiment-github-project-name: ${{ matrix.category.repository }}
          experiment-github-repository: "${{ env.GITHUB_ORGANISATION_NAME }}/${{ matrix.category.repository }}"
          experiment-programming-language: javascript
          cyclonedx-sbom-artifact-name: cyclonedx-sbom-javascript-${{ matrix.os }}
          cyclonedx-sbom-filename: sbom.json
          artifact-name: cyclonedx-sbom-osv-report-javascript-${{ matrix.os }}
          include-unit-tests: ${{ env.RUN_UNIT_TESTS }}

