name: Test Eclipse Steady SCA Action

on:
  workflow_dispatch:

jobs:
  test-action-mvn-job:
    name: Test Eclipse Steady SCA Action (Maven)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout XNIO
        uses: actions/checkout@v4
        with:
          repository: xnio/xnio
          ref: 262b9acfc8a9a85aa62a40634cc14581bf6b0d7d
          path: xnio

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: adopt
          java-version: 8

      - name: Build and Upload Maven Package
        uses: ./main/.github/actions/maven/maven-build-upload
        with:
          build-command: mvn -U -B -fae -DskipTests clean install
          path: xnio

      - name: Run Eclipse Steady (SCA)
        uses: ./main/.github/actions/sca/eclipse-steady
        with:
          language: java
          eclipse-steady-workspace-token: B774A44546001A1711E7B8F77CF9483E
          eclipse-steady-host-url: ${{ secrets.TEST_ECLIPSE_STEADY_HOST_URL }}
          project-name: xnio
          project-source-directories: api/src/main,nio-impl/src/main
          path: xnio
          build-artifact-name: sast-eclipse-steady-report-maven

  test-action-python-job:
    name: Test Eclipse Steady SCA Action (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout mycli
        uses: actions/checkout@v4
        with:
          repository: dbcli/mycli
          ref: 3bc201e4ceb62c81c2dc9ea9c0fa2cedecb8e851
          path: mycli

      - name: Install Python 3.12
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12

      - name: Install Pip Dependencies
        uses: ./main/.github/actions/python/install-pip-dependencies
        with:
          requirement-file-name: requirements-dev.txt
          path: mycli

      - name: Build and Upload Python Package
        uses: ./main/.github/actions/python/python-build-upload
        with:
          path: mycli

      - name: Run Eclipse Steady (SCA)
        uses: ./main/.github/actions/sca/eclipse-steady
        with:
          language: python
          eclipse-steady-workspace-token: D307665D82F83EBC28AE4B22BE0F0CAC
          eclipse-steady-host-url: ${{ secrets.TEST_ECLIPSE_STEADY_HOST_URL }}
          project-name: mycli
          project-source-directories: mycli
          path: mycli
          build-artifact-name: sast-eclipse-steady-report-python