name: Test OpenTelemetry Metrics Exporter Action

on:
  workflow_dispatch:

permissions:
  security-events: write

defaults:
  run:
    shell: bash

jobs:
  build-job:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Lodash
        uses: actions/checkout@v4
        with:
          repository: lodash/lodash
          ref: 1144918f3578a84fcc4986da9b806e63a6175cbb
          path: lodash

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x

      - name: Install JavaScript Dependencies
        working-directory: lodash
        run: npm ci

  test-action-job:
    name: Test OpenTelemetry Metrics Exporter Action
    needs: build-job
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Send GitHub Workflow Metrics To OpenTelemetry
        uses: ./experiment-resources/.github/actions/metrics/opentelemetry-metrics-exporter
        with:
          honeycomb-api-key: ${{ secrets.TEST_HONEYCOMB_API_KEY }}
          original-github-workflow-name: ${{ github.workflow }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
