name: Test Reporting Automated Vulnerability Results Report

on:
  workflow_dispatch:

env:
  RESOURCES_PATH: src/test/python3/resources

jobs:
  test-action:
    name: Test Automated Vulnerability Results Report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        category: [
          { programming-language: java, github-repository: H6060-Java-Logback },
          { programming-language: javascript, github-repository: H6060-JavaScript-Lodash },
          { programming-language: python, github-repository: H6060-Python-Django }
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Security Testing Tool Report (${{ matrix.category.programming-language }})
        uses: ./.github/actions/reporting/automated-vulnerability-results-report
        with:
          nvd-api-key: ${{ secrets.TEST_NVD_API_KEY }}
          opencve-username: ${{ secrets.TEST_OPENCVE_USERNAME }}
          opencve-password: ${{ secrets.TEST_OPENCVE_PASSWORD }}
          github-token: ${{ secrets.TEST_GITHUB_OAUTH_TOKEN }}
          github-organisation: seansmith39
          github-repository: ${{ matrix.category.github-repository }}
          sonarqube-url: https://sonarqube.b00158319.com
          sonarqube-token: ${{ secrets.TEST_SONARQUBE_TOKEN }}
          sonarqube-project-key: ${{ matrix.category.github-repository }}
          sast-horusec-report-filename: ${{ env.RESOURCES_PATH }}/sast-horusec/${{ matrix.category.programming-language }}/horusec-report.json
          sast-semgrep-report-filename: ${{ env.RESOURCES_PATH }}/sast-semgrep/${{ matrix.category.programming-language }}/semgrep-report.json
          sast-snyk-code-report-filename: ${{ env.RESOURCES_PATH }}/sast-snyk-code/${{ matrix.category.programming-language }}/snyk-code-report.json
          sca-grype-report-filename: ${{ env.RESOURCES_PATH }}/sca-grype/${{ matrix.category.programming-language }}/grype-report.json
          sca-snyk-report-filename: ${{ env.RESOURCES_PATH }}/sca-snyk/${{ matrix.category.programming-language }}/snyk-report.json
          sca-owasp-dependency-check-report-filename: ${{ env.RESOURCES_PATH }}/sca-owasp-dependency-check/${{ matrix.category.programming-language }}/owasp-dependency-check-report.json
          artifact-name: automated-vulnerability-results-report-${{ matrix.category.programming-language }}
          include-unit-tests: true
