name: Test OWASP Dependency Check SCA Action

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  test-action-java:
    name: Test OWASP Dependency Check SCA Action (Java)
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
        category: [
          { repository: seansmith39/H6060-Java-Logback, ref: 7ee000a0a359d239c60bb93a2f4f4ea467c38395, programming-language: java }
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Upstream Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.category.repository }}
          ref: ${{ matrix.category.ref }}
          path: upstream-repository

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Build Java Application
        uses: ./experiment-resources/.github/actions/java/java-build
        with:
          build-command: mvn -Dmaven.test.skip=true clean install
          build-directory: target
          path: jackson-databind

      - name: Run OWASP Dependency Check (SCA)
        uses: ./experiment-resources/.github/actions/sca/owasp-dependency-check
        with:
          nvd-api-key: ${{ secrets.TEST_NVD_API_KEY }}
          project-name: test-java
          artifact-name: sca-owasp-dependency-check-report-java
          path: jackson-databind

  test-action-python:
    name: Test OWASP Dependency Check SCA Action (Python)
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
        category: [
          { repository: seansmith39/H6060-Python-Urllib3, ref: d1616473df94b94f0f5ad19d2a6608cfe93b7cdf, programming-language: python }
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Upstream Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.category.repository }}
          ref: ${{ matrix.category.ref }}
          path: upstream-repository

      - name: Install Python 3.7
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.7

      - name: Install Python Dependencies
        working-directory: pillow
        env:
          GHA_PYTHON_VERSION: 3.7
        run: .ci/install.sh

      - name: Build Python Application
        uses: ./experiment-resources/.github/actions/python/python-build
        with:
          build-command: .ci/build.sh
          build-directory: build
          path: pillow

      - name: Run OWASP Dependency Check (SCA)
        uses: ./experiment-resources/.github/actions/sca/owasp-dependency-check
        with:
          nvd-api-key: ${{ secrets.TEST_NVD_API_KEY }}
          project-name: test-python
          artifact-name: sca-owasp-dependency-check-report-python
          path: pillow

  test-action-javascript:
    name: Test OWASP Dependency Check SCA Action (JavaScript)
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
        category: [
          { repository: seansmith39/H6060-JavaScript-Lodash, ref: 1144918f3578a84fcc4986da9b806e63a6175cbb, programming-language: javascript }
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Upstream Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.category.repository }}
          ref: ${{ matrix.category.ref }}
          path: upstream-repository

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x

      - name: Install JavaScript Dependencies
        working-directory: lodash
        run: npm ci

      - name: Build JavaScript Application
        uses: ./experiment-resources/.github/actions/javascript/javascript-build
        with:
          build-command: npm run build
          package-command: npm pack
          path: lodash

      - name: Run OWASP Dependency Check (SCA)
        uses: ./experiment-resources/.github/actions/sca/owasp-dependency-check
        with:
          nvd-api-key: ${{ secrets.TEST_NVD_API_KEY }}
          project-name: test-javascript
          artifact-name: sca-owasp-dependency-check-report-javascript
          path: lodash
