name: Test Reporting Automated Vulnerability Results Report

on:
  workflow_dispatch:

env:
  RESOURCES_PATH: src/test/python3/resources

jobs:
  test-action:
    name: Test Automated Vulnerability Results Report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        programming-language: [ java, javascript, python ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Security Testing Tool Report (${{ matrix.programming-language }})
        uses: ./.github/actions/reporting/automated-vulnerability-results-report
        with:
          nvd-api-key: ${{ secrets.TEST_NVD_API_KEY }}
          opencve-username: ${{ secrets.TEST_OPENCVE_USERNAME }}
          opencve-password: ${{ secrets.TEST_OPENCVE_PASSWORD }}
          sast-horusec-report-filename: ${{ env.RESOURCES_PATH }}/sast-horusec/${{ matrix.programming-language }}/horusec-report.json
          sast-semgrep-report-filename: ${{ env.RESOURCES_PATH }}/sast-semgrep/${{ matrix.programming-language }}/semgrep-report.json
          sast-snyk-code-report-filename: ${{ env.RESOURCES_PATH }}/sast-snyk-code/${{ matrix.programming-language }}/snyk-code-report.json
          sca-grype-report-filename: ${{ env.RESOURCES_PATH }}/sca-grype/${{ matrix.programming-language }}/grype-report.json
          sca-snyk-report-filename: ${{ env.RESOURCES_PATH }}/sca-snyk/${{ matrix.programming-language }}/snyk-report.json
          sca-owasp-dependency-check-report-filename: ${{ env.RESOURCES_PATH }}/sca-owasp-dependency-check/${{ matrix.programming-language }}/owasp-dependency-check-report.json
          artifact-name: automated-vulnerability-results-report-${{ matrix.programming-language }}
          include-unit-tests: true
