name: Test Security Testing Tool CSV Report Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-action-security-testing-tool-csv-report-partial:
    name: Test Security Testing Tool CSV Report (Partial)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Security Testing Tool Report
        uses: ./.github/actions/common/security-testing-tool-csv-report
        with:
          nvd-api-key: ${{ secrets.TEST_NVD_API_KEY }}
          opencve-username: ${{ secrets.TEST_OPENCVE_USERNAME }}
          opencve-password: ${{ secrets.TEST_OPENCVE_PASSWORD }}
          sast-insider-report-filename: ./.github/workflows/resources/sast-insider/report-sast-insider.json
          sca-snyk-report-filename: ./.github/workflows/resources/sca-snyk/report-sca-snyk.json
          build-artifact-name: experiment-1-security-testing-tool-results-partial

  test-action-security-testing-tool-csv-report-full:
    name: Test Security Testing Tool CSV Report (Full)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Security Testing Tool Report
        uses: ./.github/actions/common/security-testing-tool-csv-report
        with:
          nvd-api-key: ${{ secrets.TEST_NVD_API_KEY }}
          opencve-username: ${{ secrets.TEST_OPENCVE_USERNAME }}
          opencve-password: ${{ secrets.TEST_OPENCVE_PASSWORD }}
          sast-horusec-report-filename: ./.github/workflows/resources/sast-horusec/report-sast-horusec.json
          sast-insider-report-filename: ./.github/workflows/resources/sast-insider/report-sast-insider.json
          sast-semgrep-report-filename: ./.github/workflows/resources/sast-semgrep/report-sast-semgrep.json
          sast-snyk-code-report-filename: ./.github/workflows/resources/sast-snyk-code/report-sast-snyk-code.json
          sca-eclipse-steady-report-filename: ./.github/workflows/resources/sca-eclipse-steady/report-sca-eclipse-steady.json
          sca-grype-report-filename: ./.github/workflows/resources/sca-grype/report-sca-grype.json
          sca-owasp-dependency-check-report-filename: ./.github/workflows/resources/sca-owasp-dependency-check/report-sca-owasp-dependency-check.json
          sca-snyk-report-filename: ./.github/workflows/resources/sca-snyk/report-sca-snyk.json
          build-artifact-name: experiment-1-security-testing-tool-results-full
