name: Test Workflow OpenTelemetry Metrics Exporter Action

on:
  workflow_dispatch:

jobs:
  build-action-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Lodash
        uses: actions/checkout@v4
        with:
          repository: lodash/lodash
          ref: 1144918f3578a84fcc4986da9b806e63a6175cbb
          path: lodash

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x

      - name: Install Node Dependencies
        shell: bash
        working-directory: lodash
        run: npm ci

  test-send-metrics-job:
    name: Test Workflow OpenTelemetry Metrics Exporter Action
    needs: build-action-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Send GitHub Workflow Metrics To OpenTelemetry
        uses: ./main/.github/actions/common/workflow-opentelemetry-metrics-exporter
        with:
          honeycomb-api-key: ${{ secrets.TEST_HONEYCOMB_API_KEY }}
          original-github-workflow-name: ${{ github.workflow }}
