name: Test Snyk SCA Action

on: push

jobs:
  test-action-mvn-job:
    name: Test Snyk SCA Action (Maven)
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.TEST_SNYK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout TelegramBots
        uses: actions/checkout@v4
        with:
          repository: rubenlagus/TelegramBots
          ref: e9add4fd0d33f8b62b9d986b2716e7e5893cb817
          path: telegrambots

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: "Build and Upload Maven Package"
        uses: ./main/.github/actions/maven/maven-build-upload
        with:
          build-command: clean install
          path: telegrambots

      - name: "Run Snyk (SCA)"
        uses: ./main/.github/actions/sca/snyk
        with:
          language: java
          path: telegrambots
          build-artifact-name: sast-snyk-report-maven

  test-action-python-job:
    name: Test Snyk SCA Action (Python)
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.TEST_SNYK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout Clearml
        uses: actions/checkout@v4
        with:
          repository: allegroai/clearml
          ref: f2674669265a56a8ecaed3d0147f319ee136a231
          path: clearml

      - name: Install Python 3.8
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.8

      - name: "Install Pip Dependencies"
        uses: ./main/.github/actions/python/install-pip-dependencies
        with:
          requirement-file-name: requirements.txt
          extra-pip-packages: setuptools
          path: clearml

      - name: "Build and Upload Python Package"
        uses: ./main/.github/actions/python/python-build-upload
        with:
          path: clearml

      - name: "Run Snyk (SCA)"
        uses: ./main/.github/actions/sca/snyk
        with:
          language: python
          snyk-package-manager: pip
          snyk-file-to-scan: requirements.txt
          path: clearml
          build-artifact-name: sast-snyk-report-python
