name: Test Reporting Manual Vulnerability Results Report

on:
  workflow_dispatch:

jobs:
  test-action:
    name: Test Manual Vulnerability Results Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Security Testing Tool Report (SCA)
        uses: ./.github/actions/reporting/manual-vulnerability-results-report
        with:
          nvd-api-key: ${{ secrets.TEST_NVD_API_KEY }}
          opencve-username: ${{ secrets.TEST_OPENCVE_USERNAME }}
          opencve-password: ${{ secrets.TEST_OPENCVE_PASSWORD }}
          security-tool-name: Eclipse Steady
          cve-ids: CVE-2023-52428,CVE-2021-44228
          artifact-name: manual-vulnerability-results-report-sca
          include-unit-tests: true

      - name: Create Security Testing Tool Report (SAST)
        uses: ./.github/actions/reporting/manual-vulnerability-results-report
        with:
          nvd-api-key: ${{ secrets.TEST_NVD_API_KEY }}
          opencve-username: ${{ secrets.TEST_OPENCVE_USERNAME }}
          opencve-password: ${{ secrets.TEST_OPENCVE_PASSWORD }}
          security-tool-name: SonarQube
          cwe-ids: CWE-798,CWE-120
          artifact-name: manual-vulnerability-results-report-sast
          include-unit-tests: true
