name: Test SonarQube SAST Action

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  test-action-java:
    name: Test SonarQube SAST Action (Java)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Jackson-Databind Repository
        uses: actions/checkout@v4
        with:
          repository: FasterXML/jackson-databind
          ref: d0e9952ea70d1af5c512322a32456f237afb9e9b
          path: jackson-databind

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Build Java Application
        uses: ./experiment-resources/.github/actions/java/java-build
        with:
          build-command: mvn -Dmaven.test.skip=true clean install
          build-directory: target
          path: jackson-databind

      - name: Run SonarQube (SAST)
        uses: ./experiment-resources/.github/actions/sast/sonarqube
        with:
          programming-language: java
          sonarqube-token: ${{ secrets.TEST_SONARQUBE_TOKEN }}
          sonarqube-url: https://sonarqube.b00158319.com
          sonarqube-username: ${{ secrets.TEST_SONARQUBE_USERNAME }}
          sonarqube-password: ${{ secrets.TEST_SONARQUBE_PASSWORD }}
          sonarqube-project-key: test-java
          artifact-name: sast-sonarqube-report-java
          path: jackson-databind

  test-action-python:
    name: Test SonarQube SAST Action (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Pillow Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Python-Pillow
          ref: 722b5d3350fbbb599fd3966e08e55547a2656cd7
          path: pillow

      - name: Run SonarQube (SAST)
        uses: ./experiment-resources/.github/actions/sast/sonarqube
        with:
          programming-language: python
          sonarqube-token: ${{ secrets.TEST_SONARQUBE_TOKEN }}
          sonarqube-url: https://sonarqube.b00158319.com
          sonarqube-username: ${{ secrets.TEST_SONARQUBE_USERNAME }}
          sonarqube-password: ${{ secrets.TEST_SONARQUBE_PASSWORD }}
          sonarqube-project-key: test-python
          artifact-name: sast-sonarqube-report-python
          path: pillow

  test-action-javascript:
    name: Test SonarQube SAST Action (JavaScript)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Lodash Repository
        uses: actions/checkout@v4
        with:
          repository: lodash/lodash
          ref: 1144918f3578a84fcc4986da9b806e63a6175cbb
          path: lodash

      - name: Run SonarQube (SAST)
        uses: ./experiment-resources/.github/actions/sast/sonarqube
        with:
          programming-language: javascript
          sonarqube-token: ${{ secrets.TEST_SONARQUBE_TOKEN }}
          sonarqube-url: ${{ secrets.TEST_SONARQUBE_URL }}
          sonarqube-username: ${{ secrets.TEST_SONARQUBE_USERNAME }}
          sonarqube-password: ${{ secrets.TEST_SONARQUBE_PASSWORD }}
          sonarqube-project-key: test-javascript
          artifact-name: sast-sonarqube-report-javascript
          path: lodash
