name: Test Snyk SCA Action

on: push

jobs:
  test-action-mvn-job:
    name: Test Snyk SCA Action (Maven)
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.TEST_SNYK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout TelegramBots
        uses: actions/checkout@v4
        with:
          repository: rubenlagus/TelegramBots
          ref: e9add4fd0d33f8b62b9d986b2716e7e5893cb817
          path: telegrambots

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.12.0
        with:
          java-version: 17
          maven-version: 3.9.6

      - name: "Build and Upload Maven Package"
        uses: ./main/.github/actions/maven/maven-build-upload
        with:
          build-command: -U -B -fae -DskipTests clean install
          path: telegrambots

      - name: "Run Snyk (SCA)"
        uses: ./main/.github/actions/sca/snyk
        with:
          language: java
          path: telegrambots
          build-artifact-name: sast-snyk-report-maven

  test-action-python-job:
    name: Test Snyk SCA Action (Python)
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.TEST_SNYK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout Clearml
        uses: actions/checkout@v4
        with:
          repository: dbcli/mycli
          ref: 3bc201e4ceb62c81c2dc9ea9c0fa2cedecb8e851
          path: mycli

      - name: Install Python 3.12
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12

      - name: "Install Pip Dependencies"
        uses: ./main/.github/actions/python/install-pip-dependencies
        with:
          requirement-file-name: requirements-dev.txt
          path: mycli

      - name: "Build and Upload Python Package"
        uses: ./main/.github/actions/python/python-build-upload
        with:
          path: mycli

      - name: "Run Snyk (SCA)"
        uses: ./main/.github/actions/sca/snyk
        with:
          language: python
          snyk-package-manager: pip
          snyk-file-to-scan: requirements-dev.txt
          path: mycli
          build-artifact-name: sast-snyk-report-python
