name: Test Semgrep SAST Action

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  test-action-java:
    name: Test Semgrep SAST Action (Java)
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.TEST_SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout Jackson-Databind Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Java-Jackson-Databind
          ref: 1acb8ffe6eb20005114bfe18cfd5809b443789c2
          path: jackson-databind

      - name: Run Semgrep (SAST)
        uses: ./main/.github/actions/sast/semgrep
        with:
          language: java
          path: jackson-databind
          artifact-name: sast-semgrep-report-java

  test-action-python:
    name: Test Semgrep SAST Action (Python)
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.TEST_SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout Pillow Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Python-Pillow
          ref: 722b5d3350fbbb599fd3966e08e55547a2656cd7
          path: pillow

      - name: Run Semgrep (SAST)
        uses: ./main/.github/actions/sast/semgrep
        with:
          language: python
          path: pillow
          artifact-name: sast-semgrep-report-python

  test-action-javascript:
    name: Test Semgrep SAST Action (JavaScript)
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.TEST_SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout Lodash Repository
        uses: actions/checkout@v4
        with:
          repository: lodash/lodash
          ref: 1144918f3578a84fcc4986da9b806e63a6175cbb
          path: lodash

      - name: Run Semgrep (SAST)
        uses: ./main/.github/actions/sast/semgrep
        with:
          language: javascript
          path: lodash
          artifact-name: sast-semgrep-report-javascript
