name: Test DeepSource SAST Action

on:
  workflow_dispatch:

permissions:
  security-events: write

defaults:
  run:
    shell: bash
    
jobs:
  test-action-java:
    name: Test DeepSource SAST Action (Java)
    runs-on: ubuntu-latest
    env:
      DEEPSOURCE_DSN: ${{ secrets.TEST_JAVA_DEEPSOURCE_DSN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Jackson-Databind
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Java-Jackson-Databind
          ref: b18537249abc2f1c59f68c78aa99c59113261135
          path: jackson-databind

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Build Java Application
        uses: ./experiment-resources/.github/actions/java/java-build
        with:
          build-command: mvn -Dmaven.test.skip=true clean install
          build-directory: target
          path: jackson-databind

      - name: Run Java Application Tests
        working-directory: jackson-databind
        run: mvn -Dmaven.test.failure.ignore=true test

      - name: Run DeepSource (SAST)
        uses: ./experiment-resources/.github/actions/sast/deepsource
        with:
          programming-language: java
          coverage-file: target/site/jacoco/jacoco.xml
          path: jackson-databind

  test-action-python:
    name: Test DeepSource SAST Action (Python)
    runs-on: ubuntu-latest
    env:
      DEEPSOURCE_DSN: ${{ secrets.TEST_PYTHON_DEEPSOURCE_DSN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Pillow Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Python-Pillow
          ref: 00fe2c1ff01a4219f0994d5540470774a2960d13
          path: pillow

      - name: Install Python 3.7
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.7

      - name: Install Python Dependencies
        working-directory: pillow
        env:
          GHA_PYTHON_VERSION: 3.7
        run: .ci/install.sh

      - name: Build Python Application
        uses: ./experiment-resources/.github/actions/python/python-build
        with:
          build-command: .ci/build.sh
          build-directory: build
          path: pillow

      - name: Run Python Application Tests
        working-directory: pillow
        env:
          PYTHONOPTIMIZE: 2
        run: xvfb-run -s '-screen 0 1024x768x24' .ci/test.sh

      - name: Run DeepSource (SAST)
        uses: ./experiment-resources/.github/actions/sast/deepsource
        with:
          programming-language: python
          coverage-file: coverage.xml
          path: pillow
