name: Test Java Dependency Tree Action

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  test-action-job:
    name: Test Java Dependency Tree Action
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Jackson-Databind
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Java-Jackson-Databind
          ref: 1acb8ffe6eb20005114bfe18cfd5809b443789c2
          path: jackson-databind

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Create Java Dependency Tree
        uses: ./experiment-resources/.github/actions/java/java-dependency-tree
        with:
          path: jackson-databind
