name: Experiment 3 - JavaScript Scanning

on:
  workflow_call:
    inputs:
      sast-sonarqube-enabled:
        description: Enable SonarQube scan (SAST)
        type: boolean
        required: false
        default: true

      sast-semgrep-enabled:
        description: Enable Semgrep scan (SAST)
        type: boolean
        required: false
        default: true

      sast-horusec-enabled:
        description: Enable Horusec scan (SAST)
        type: boolean
        required: false
        default: true

      sast-codeql-enabled:
        description: Enable CodeQL scan (SAST)
        type: boolean
        required: false
        default: true

      sast-snyk-code-enabled:
        description: Enable Snyk Code scan (SAST)
        type: boolean
        required: false
        default: true

      sca-snyk-enabled:
        description: Enable Snyk scan (SCA)
        type: boolean
        required: false
        default: true

      sca-owasp-dependency-check-enabled:
        description: Enable OWASP Dependency Check scan (SCA)
        type: boolean
        required: false
        default: true

      sca-grype-enabled:
        description: Enable Grype scan (SCA)
        type: boolean
        required: false
        default: true

      project-name:
        description: Name of project to be scanned
        type: string
        required: false

      build-directory:
        description: Name of project build directory
        type: string
        required: false

      coverage-report-name:
        description: Name of coverage report
        type: string
        required: false

      node-version:
        description: Node.js version to install
        type: string
        required: false
        default: 16.x

permissions:
  security-events: write
  
defaults:
  run:
    shell: bash

jobs:
  sast-sonarqube:
    name: Run SonarQube (SAST)
    if: ${{ inputs.sast-sonarqube-enabled == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: experiment-resources-repo

      - name: Checkout Project Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: project-repo

      - name: Download Build
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          name: javascript-build
          path: project-repo/${{ inputs.build-directory }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: in_progress
          commit: ${{ github.event.workflow_run.head_commit.id }}

      - name: Check For File Existence
        if: ${{ inputs.build-directory != '' }}
        uses: andstor/file-existence-action@v3
        with:
          files: project-repo/${{ inputs.build-directory }}
          fail: true

      - name: Run SonarQube (SAST)
        uses: ./experiment-resources-repo/.github/actions/sast/sonarqube
        with:
          programming-language: javascript
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-host-url: ${{ secrets.SONAR_HOST_URL}}
          sonar-username: ${{ secrets.SONAR_USERNAME }}
          sonar-password: ${{ secrets.SONAR_PASSWORD }}
          sonar-project-name: ${{ inputs.project-name }}
          path: project-repo

  sast-semgrep:
    name: Run Semgrep (SAST)
    if: ${{ inputs.sast-semgrep-enabled == true }}
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: experiment-resources-repo

      - name: Checkout Project Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: project-repo

      - name: Run Semgrep (SAST)
        uses: ./experiment-resources-repo/.github/actions/sast/semgrep
        with:
          programming-language: python
          path: project-repo

  sast-horusec:
    name: Run Horusec (SAST)
    if: ${{ inputs.sast-horusec-enabled == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: experiment-resources-repo

      - name: Checkout Project Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: project-repo

      - name: Run Horusec (SAST)
        uses: ./experiment-resources-repo/.github/actions/sast/horusec
        with:
          path: project-repo

  sast-codeql:
    name: Run CodeQL (SAST)
    if: ${{ inputs.sast-codeql-enabled == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: experiment-resources-repo

      - name: Checkout Project Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: project-repo

      - name: Run CodeQL (SAST)
        uses: ./experiment-resources-repo/.github/actions/sast/codeql
        with:
          programming-language: javascript
          path: project-repo

  sast-snyk-code:
    name: Run Snyk Code (SAST)
    if: ${{ inputs.sast-snyk-code-enabled == true }}
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: experiment-resources-repo

      - name: Checkout Project Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: project-repo

      - name: Run Snyk Code (SAST)
        uses: ./experiment-resources-repo/.github/actions/sast/snyk-code
        with:
          path: project-repo

  sca-snyk:
    name: Run Snyk (SCA)
    if: ${{ inputs.sca-snyk-enabled == true }}
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: experiment-resources-repo

      - name: Checkout Project Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: project-repo

      - name: Download Build
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          name: javascript-build
          path: project-repo/${{ inputs.build-directory }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: in_progress
          commit: ${{ github.event.workflow_run.head_commit.id }}
          
      - name: Check For File Existence
        if: ${{ inputs.build-directory != '' }}
        uses: andstor/file-existence-action@v3
        with:
          files: project-repo/${{ inputs.build-directory }}
          fail: true

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install JavaScript Dependencies
        run: npm ci

      - name: Run Snyk (SCA)
        uses: ./experiment-resources-repo/.github/actions/sca/snyk
        with:
          programming-language: javascript
          path: project-repo

  sca-owasp-dependency-check:
    name: Run OWASP Dependency Check (SCA)
    if: ${{ inputs.sca-owasp-dependency-check-enabled == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: experiment-resources-repo

      - name: Checkout Project Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: project-repo

      - name: Download Build
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          name: javascript-build
          path: project-repo/${{ inputs.build-directory }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: in_progress
          commit: ${{ github.event.workflow_run.head_commit.id }}

      - name: Check For File Existence
        if: ${{ inputs.build-directory != '' }}
        uses: andstor/file-existence-action@v3
        with:
          files: project-repo/${{ inputs.build-directory }}
          fail: true

      - name: Run OWASP Dependency Check (SCA)
        uses: ./experiment-resources-repo/.github/actions/sca/owasp-dependency-check
        with:
          nvd-api-key: ${{ secrets.NVD_API_KEY }}
          project-name: ${{ inputs.project-name }}
          path: project-repo

  sca-grype:
    name: Run Grype (SCA)
    if: ${{ inputs.sca-grype-enabled == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: experiment-resources-repo

      - name: Checkout Project Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: project-repo

      - name: Download Build
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          name: javascript-build
          path: project-repo/${{ inputs.build-directory }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: in_progress
          commit: ${{ github.event.workflow_run.head_commit.id }}

      - name: Check For File Existence
        if: ${{ inputs.build-directory != '' }}
        uses: andstor/file-existence-action@v3
        with:
          files: project-repo/${{ inputs.build-directory }}
          fail: true

      - name: Run Grype (SCA)
        uses: ./experiment-resources-repo/.github/actions/sca/grype
        with:
          path: project-repo

  create-security-testing-tool-report:
    name: Create Security Testing Tool Report
    runs-on: ubuntu-latest
    needs: [
      sast-sonarqube,
      sast-semgrep,
      sast-horusec,
      sast-codeql,
      sast-snyk-code,
      sca-eclipse-steady,
      sca-snyk,
      sca-owasp-dependency-check,
      sca-grype
    ]
    if: ${{ ! failure() && ! cancelled() }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources

      - name: Download All Build Artifacts
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: in_progress
          commit: ${{ github.event.workflow_run.head_commit.id }}

      - name: Create Security Testing Tool Report
        uses: ./.github/actions/common/security-testing-tool-csv-report
        with:
          nvd-api-key: ${{ secrets.NVD_API_KEY }}
          opencve-username: ${{ secrets.OPENCVE_USERNAME }}
          opencve-password: ${{ secrets.OPENCVE_PASSWORD }}
          sast-horusec-report-filename: sast-horusec-report/horusec-report.json
          sast-semgrep-report-filename: sast-semgrep-report/semgrep-report.json
          sast-snyk-code-report-filename: sast-snyk-code-report/snyk-code-report.json
          sca-eclipse-steady-report-filename: sca-eclipse-steady-report/vulas-report.json
          sca-grype-report-filename: sca-grype-report/results.json
          sca-owasp-dependency-check-report-filename: sca-owasp-dependency-check-report/dependency-check-report.json
          sca-snyk-report-filename: sca-snyk-report/snyk-report.json

  export-opentelemetry-metrics:
    name: Export GitHub Action OpenTelemetry Metrics
    if: ${{ ! failure() && ! cancelled() }}
    needs: create-security-testing-tool-report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current GitHub Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources

      - name: Export GitHub Action OpenTelemetry Metrics
        uses: ./.github/actions/metrics/opentelemetry-metrics-exporter
        with:
          honeycomb-api-key: ${{ secrets.HONEYCOMB_API_KEY }}
          original-github-workflow-name: ${{ github.workflow }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
