name: Experiment 1 - SCA Scanning Maven

on:
  workflow_call:
    inputs:
      eclipse-steady-scan-enabled:
        description: 'Enable Eclipse Steady scan'
        type: boolean
        required: false
        default: true
      snyk-scan-enabled:
        description: 'Enable Snyk scan'
        type: boolean
        required: false
        default: true
      owasp-dependency-scan-enabled:
        description: 'Enable OWASP Dependency Check scan'
        type: boolean
        required: false
        default: true
      project-name:
        description: 'Name of project being scanned'
        type: string
        required: true
      java-version:
        description: 'Java version to build Maven project'
        type: string
        required: false
        default: 8
      java-distribution:
        description: 'Java distribution to build Maven project'
        type: string
        required: false
        default: adopt
      maven-setup-required:
        description: 'Enable Maven setup'
        type: boolean
        required: false
        default: false
      mvn-build-artifact:
        description: 'Maven build artifact'
        type: string
        required: false
        default: maven-build
      snyk-sarif-enabled:
        description: 'Enable Snyk SARIF output'
        type: boolean
        required: false
        default: true

jobs:
  eclipse_steady_scan:
    name: Run SCA Eclipse Steady Scan
    if: ${{ inputs.eclipse-steady-scan-enabled == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Maven Build
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          name: ${{ inputs.mvn-build-artifact }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: in_progress
          commit: ${{ github.event.workflow_run.head_commit.id }}

      - name: Extract Maven Build
        shell: bash
        run: tar -xzf ${{ inputs.mvn-build-artifact }}.tgz -C ~

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: Setup Maven Action
        if: ${{ inputs.maven-setup-required == true }}
        uses: s4u/setup-maven-action@v1.12.0
        with:
          java-version: ${{ inputs.java-version }}
          maven-version: 3.9.6

      - name: Run Eclipse Steady Scan
        shell: bash
        run: |
          mvn -Dsteady compile steady:app
          mvn -Dsteady steady:report

      - name: Upload Eclipse Steady Scan Json Results
        uses: actions/upload-artifact@v4
        with:
          name: eclipse-steady-scan-reports-json
          path: '**/vulas-report.json'

      - name: Upload Eclipse Steady Scan Html Results
        uses: actions/upload-artifact@v4
        with:
          name: eclipse-steady-scan-reports-html
          path: '**/vulas-report.html'

  snyk_scan:
    name: Run SCA Snyk Scan
    if: ${{ inputs.snyk-scan-enabled == true }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Maven Build
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          name: ${{ inputs.mvn-build-artifact }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: in_progress
          commit: ${{ github.event.workflow_run.head_commit.id }}

      - name: Extract Maven Build
        shell: bash
        run: tar -xzf ${{ inputs.mvn-build-artifact }}.tgz -C ~

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4.0.2

      - name: Install Snyk CLI
        shell: bash
        run: npm install snyk -g

      # Snyk returns exit code 1 if vulnerabilities are found
      - name: Run Snyk Scan
        shell: bash
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          if [[ "${{ inputs.snyk-sarif-enabled }}" == "true" ]]; then
            snyk test --all-projects --dev --sarif-file-output=snyk.sarif --json > snyk.json || EXIT_CODE=$?
          else
            snyk test --all-projects --dev --json > snyk.json || EXIT_CODE=$?
          fi
          if [ $EXIT_CODE -eq 1 ]; then exit 0; fi

      - name: Upload Snyk Scan Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snyk-scan-report
          path: '**/snyk.json'

      - name: Upload Snyk Result To GitHub Code Scanning
        if: ${{ inputs.snyk-sarif-enabled == true }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          category: snyk-sca-tool

  owasp_dependency_check:
    name: Run SCA OWASP Dependency Check
    if: ${{ inputs.owasp-dependency-scan-enabled == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Maven Build
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          name: ${{ inputs.mvn-build-artifact }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: in_progress
          commit: ${{ github.event.workflow_run.head_commit.id }}

      - name: Extract Maven Build
        shell: bash
        run: tar -xzf ${{ inputs.mvn-build-artifact }}.tgz -C ~

      - name: Run OWASP Dependency Check (JSON)
        uses: dependency-check/Dependency-Check_Action@1.1.0
        with:
          project: ${{ inputs.project-name }}
          path: .
          format: JSON
          args: >
            --enableRetired

      - name: Run OWASP Dependency Check (HTML)
        uses: dependency-check/Dependency-Check_Action@1.1.0
        with:
          project: ${{ inputs.project-name }}
          path: .
          format: HTML
          args: >
            --enableRetired

      - name: Upload OWASP Dependency Check Results
        uses: actions/upload-artifact@v4
        with:
          name: OWASP Dependency Check Report
          path: ${{ github.workspace }}/reports
