name: Experiment 1 - Python Scanning

on:
  workflow_call:
    inputs:
      sast-sonarqube-enabled:
        description: Enable SonarQube scan (SAST)
        type: boolean
        required: false
        default: true

      sast-semgrep-enabled:
        description: Enable Semgrep scan (SAST)
        type: boolean
        required: false
        default: true

      sast-deepsource-enabled:
        description: Enable Deepsource scan (SAST)
        type: boolean
        required: false
        default: true

      sast-horusec-enabled:
        description: Enable Horusec scan (SAST)
        type: boolean
        required: false
        default: true

      sast-codeql-enabled:
        description: Enable CodeQL scan (SAST)
        type: boolean
        required: false
        default: true

      sast-snyk-code-enabled:
        description: Enable Snyk Code scan (SAST)
        type: boolean
        required: false
        default: true

      sca-eclipse-steady-enabled:
        description: Enable Eclipse Steady scan (SCA)
        type: boolean
        required: false
        default: true

      sca-snyk-enabled:
        description: Enable Snyk scan (SCA)
        type: boolean
        required: false
        default: true

      sca-owasp-dependency-check-enabled:
        description: Enable OWASP Dependency Check scan (SCA)
        type: boolean
        required: false
        default: true

      sca-grype-enabled:
        description: Enable Grype scan (SCA)
        type: boolean
        required: false
        default: true

      eclipse-steady-workspace-token:
        description: Token assigned to Eclipse Steady project workspace
        type: string
        required: false

      eclipse-steady-project-source-directories:
        description: Source directories to scan using Eclipse Steady
        type: string
        required: false

      project-name:
        description: Name of project to be scanned
        type: string
        required: false

      project-build-dir:
        description: Name of project build directory
        type: string
        required: false
        default: dist

      coverage-filename:
        description: Name of test coverage file
        type: string
        required: false
        default: coverage.xml

      sca-file-to-scan:
        description: File to scan
        type: string
        required: false
        default: requirements.txt

jobs:
  create-pip-dependency-tree:
    name: Create Pip Dependency Tree
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current GitHub Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: main-repo

      - name: Checkout Calling GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: upstream-repo

      - name: Install Python 3.12
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12

      - name: Create Pip Dependency Tree
        uses: ./main-repo/.github/actions/python/pip-dependency-tree
        with:
          path: upstream-repo

  sast-sonarqube:
    name: Run SonarQube (SAST)
    if: ${{ inputs.sast-sonarqube-enabled == true }}
    runs-on: ubuntu-latest
    needs: create-pip-dependency-tree
    steps:
      - name: Checkout Current GitHub Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: main-repo

      - name: Checkout Calling GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: upstream-repo

      # Unzips to upstream-repo/python-build.tgz
      - name: Download Build
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          name: python-build
          path: upstream-repo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: in_progress
          commit: ${{ github.event.workflow_run.head_commit.id }}

      - name: Extract Build
        uses: ./main-repo/.github/actions/common/extract-build-artifact
        with:
          build-artifact-name: python-build
          path: upstream-repo

      - name: Check For File Existence
        uses: andstor/file-existence-action@v3
        with:
          files: upstream-repo/${{ inputs.project-build-dir }}
          fail: true

      - name: Run SonarQube (SAST)
        uses: ./main-repo/.github/actions/sast/sonarqube
        with:
          language: python
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-host-url: ${{ secrets.SONAR_HOST_URL}}
          sonar-username: ${{ secrets.SONAR_USERNAME }}
          sonar-password: ${{ secrets.SONAR_PASSWORD }}
          sonar-project-name: ${{ inputs.project-name }}
          path: upstream-repo

  sast-semgrep:
    name: Run Semgrep (SAST)
    if: ${{ inputs.sast-semgrep-enabled == true }}
    runs-on: ubuntu-latest
    needs: create-pip-dependency-tree
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout Current GitHub Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: main-repo

      - name: Checkout Calling GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: upstream-repo

      - name: Run Semgrep (SAST)
        uses: ./main-repo/.github/actions/sast/semgrep
        with:
          language: python
          path: upstream-repo

  sast-deepsource:
    name: Run Deepsource (SAST)
    if: ${{ inputs.sast-deepsource-enabled == true }}
    runs-on: ubuntu-latest
    needs: create-pip-dependency-tree
    env:
      DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
    steps:
      - name: Checkout Current GitHub Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: main-repo

      - name: Checkout Calling GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: upstream-repo

      - name: Download Coverage
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          name: coverage-report
          path: upstream-repo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: in_progress
          commit: ${{ github.event.workflow_run.head_commit.id }}

      - name: Check For File Existence
        uses: andstor/file-existence-action@v3
        with:
          files: upstream-repo/${{ inputs.coverage-filename }}
          fail: true

      - name: Run Deepsource (SAST)
        uses: ./main-repo/.github/actions/sast/deepsource
        with:
          language: python
          coverage-file: ${{ inputs.coverage-filename }}
          path: upstream-repo

  sast-horusec:
    name: Run Horusec (SAST)
    if: ${{ inputs.sast-horusec-enabled == true }}
    runs-on: ubuntu-latest
    needs: create-pip-dependency-tree
    steps:
      - name: Checkout Current GitHub Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: main-repo

      - name: Checkout Calling GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: upstream-repo

      - name: Run Horusec (SAST)
        uses: ./main-repo/.github/actions/sast/horusec
        with:
          path: upstream-repo

  sast-codeql:
    name: Run CodeQL (SAST)
    if: ${{ inputs.sast-codeql-enabled == true }}
    runs-on: ubuntu-latest
    needs: create-pip-dependency-tree
    steps:
      - name: Checkout Current GitHub Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: main-repo

      - name: Checkout Calling GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: upstream-repo

      - name: Run CodeQL (SAST)
        uses: ./main-repo/.github/actions/sast/codeql
        with:
          language: python
          path: upstream-repo

  sast-snyk-code:
    name: Run Snyk Code (SAST)
    if: ${{ inputs.sast-snyk-code-enabled == true }}
    runs-on: ubuntu-latest
    needs: create-pip-dependency-tree
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout Current GitHub Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: main-repo

      - name: Checkout Calling GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: upstream-repo

      - name: Run Snyk Code (SAST)
        uses: ./main-repo/.github/actions/sast/snyk-code
        with:
          path: upstream-repo

  sca-eclipse-steady:
    name: Run Eclipse Steady (SCA)
    if: ${{ inputs.sca-eclipse-steady-enabled == true }}
    runs-on: ubuntu-latest
    needs: create-pip-dependency-tree
    steps:
      - name: Checkout Current GitHub Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: main-repo

      - name: Checkout Calling GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: upstream-repo

      # Unzips to upstream-repo/python-build.tgz
      - name: Download Build
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          name: python-build
          path: upstream-repo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: in_progress
          commit: ${{ github.event.workflow_run.head_commit.id }}

      - name: Extract Build
        uses: ./main-repo/.github/actions/common/extract-build-artifact
        with:
          build-artifact-name: python-build
          path: upstream-repo

      - name: Check For File Existence
        uses: andstor/file-existence-action@v3
        with:
          files: upstream-repo/${{ inputs.project-build-dir }}
          fail: true

      - name: Run Eclipse Steady (SCA)
        uses: ./main-repo/.github/actions/sca/eclipse-steady
        with:
          language: python
          eclipse-steady-workspace-token: ${{ inputs.eclipse-steady-workspace-token }}
          eclipse-steady-host-url: ${{ secrets.ECLIPSE_STEADY_HOST_URL }}
          project-name: ${{ inputs.project-name }}
          project-source-directories: ${{ inputs.eclipse-steady-project-source-directories }}
          path: upstream-repo

  sca-snyk:
    name: Run Snyk (SCA)
    if: ${{ inputs.sca-snyk-enabled == true }}
    runs-on: ubuntu-latest
    needs: create-pip-dependency-tree
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout Current GitHub Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: main-repo

      - name: Checkout Calling GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: upstream-repo

      # Unzips to upstream-repo/python-build.tgz
      - name: Download Build
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          name: python-build
          path: upstream-repo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: in_progress
          commit: ${{ github.event.workflow_run.head_commit.id }}

      - name: Extract Build
        uses: ./main-repo/.github/actions/common/extract-build-artifact
        with:
          build-artifact-name: python-build
          path: upstream-repo

      - name: Check For File Existence
        uses: andstor/file-existence-action@v3
        with:
          files: upstream-repo/${{ inputs.project-build-dir }}
          fail: true

      - name: Install Pip Dependencies
        uses: ./main-repo/.github/actions/python/install-pip-dependencies
        with:
          requirement-file-name: ${{ inputs.sca-file-to-scan }}
          path: upstream-repo

      - name: Run Snyk (SCA)
        uses: ./main-repo/.github/actions/sca/snyk
        with:
          language: python
          path: upstream-repo
          snyk-package-manager: pip
          snyk-file-to-scan: ${{ inputs.sca-file-to-scan }}

  sca-owasp-dependency-check:
    name: Run OWASP Dependency Check (SCA)
    if: ${{ inputs.sca-owasp-dependency-check-enabled == true }}
    runs-on: ubuntu-latest
    needs: create-pip-dependency-tree
    steps:
      - name: Checkout Current GitHub Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: main-repo

      - name: Checkout Calling GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: upstream-repo

      # Unzips to upstream-repo/python-build.tgz
      - name: Download Build
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          name: python-build
          path: upstream-repo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: in_progress
          commit: ${{ github.event.workflow_run.head_commit.id }}

      - name: Extract Build
        uses: ./main-repo/.github/actions/common/extract-build-artifact
        with:
          build-artifact-name: python-build
          path: upstream-repo

      - name: Check For File Existence
        uses: andstor/file-existence-action@v3
        with:
          files: upstream-repo/${{ inputs.project-build-dir }}
          fail: true

      - name: Run OWASP Dependency Check (SCA)
        uses: ./main-repo/.github/actions/sca/owasp-dependency-check
        with:
          project-name: ${{ inputs.project-name }}
          nvd-api-key: ${{ secrets.NVD_API_KEY }}
          path: upstream-repo

  sca-grype:
    name: Run Grype (SCA)
    if: ${{ inputs.sca-grype-enabled == true }}
    runs-on: ubuntu-latest
    needs: create-pip-dependency-tree
    steps:
      - name: Checkout Current GitHub Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources
          path: main-repo

      - name: Checkout Calling GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: upstream-repo

      # Unzips to upstream-repo/python-build.tgz
      - name: Download Build
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          name: python-build
          path: upstream-repo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: in_progress
          commit: ${{ github.event.workflow_run.head_commit.id }}

      - name: Extract Build
        uses: ./main-repo/.github/actions/common/extract-build-artifact
        with:
          build-artifact-name: python-build
          path: upstream-repo

      - name: Check For File Existence
        uses: andstor/file-existence-action@v3
        with:
          files: upstream-repo/${{ inputs.project-build-dir }}
          fail: true

      - name: Install Pip Dependencies
        uses: ./main-repo/.github/actions/python/install-pip-dependencies
        with:
          requirement-file-name: ${{ inputs.sca-file-to-scan }}
          path: upstream-repo

      - name: Run Grype (SCA)
        uses: ./main-repo/.github/actions/sca/grype
        with:
          path: upstream-repo

  create-security-testing-tool-report:
    name: Create Security Testing Tool Report
    runs-on: ubuntu-latest
    needs: [
      sast-sonarqube,
      sast-semgrep,
      sast-deepsource,
      sast-horusec,
      sast-codeql,
      sast-snyk-code,
      sca-eclipse-steady,
      sca-snyk,
      sca-owasp-dependency-check,
      sca-grype
    ]
    if: ${{ ! failure() && ! cancelled() }}
    steps:
      - name: Checkout Current GitHub Repository
        uses: actions/checkout@v4
        with:
          repository: seansmith39/H6060-Experiment-Resources

      - name: Download All Build Artifacts
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: in_progress
          commit: ${{ github.event.workflow_run.head_commit.id }}

      - name: Create Security Testing Tool Report
        uses: ./.github/actions/common/security-testing-tool-csv-report
        with:
          nvd-api-key: ${{ secrets.NVD_API_KEY }}
          opencve-username: ${{ secrets.OPENCVE_USERNAME }}
          opencve-password: ${{ secrets.OPENCVE_PASSWORD }}
          sast-horusec-report-filename: sast-horusec-report/horusec-report.json
          sast-semgrep-report-filename: sast-semgrep-report/semgrep-report.json
          sast-snyk-code-report-filename: sast-snyk-code-report/snyk-code-report.json
          sca-eclipse-steady-report-filename: sca-eclipse-steady-report/vulas-report.json
          sca-grype-report-filename: sca-grype-report/results.json
          sca-owasp-dependency-check-report-filename: sca-owasp-dependency-check-report/dependency-check-report.json
          sca-snyk-report-filename: sca-snyk-report/snyk-report.json
